services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    volumes:
      - D:\project\volumes\postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - service-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    volumes:
      - D:\project\volumes\ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - service-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    environment:
      PGADMIN_DEFAULT_EMAIL: yxchen0323@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
    volumes:
      - D:\project\volumes\pgadmin_data:/var/lib/
    depends_on:
      - postgres
    networks:
      - service-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - D:\project\NLDQS-MCP\nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pgadmin
      - postgres
      - ollama
    networks:
      - service-network
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
  pgadmin_data:
  nginx_data:

networks:
  service-network:
    external: true
    driver: bridge
    name: service-network