version: '3.8'

services:
  fastapi:
    build: ./api
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    networks:
      - 911emergency-network
    restart: unless-stopped

networks:
  911emergency-network:
    external: true
    driver: bridge
    name: 911emergency-network