version: "3.9"
services:
  dqs-app:
    build:
      context: ./app
      dockerfile: Dockerfile.dqs
    container_name: dqs_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./app/uploaded_files:/app/app/uploaded_files
      - D:/project/transformer_model/Qwen2_5-Coder-3B:/app/llm
    deploy: {}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia